// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;

import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.auto.NamedCommands;
import com.pathplanner.lib.events.EventTrigger;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj2.command.StartEndCommand;
import com.revrobotics.RelativeEncoder;
import com.revrobotics.spark.SparkLowLevel.MotorType;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.RunCommand;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * This class is where the bulk of the robot should be declared. Since
 * Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in
 * the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of
 * the robot
 * (including subsystems, commands, and button mappings) should be declared
 * here.
 */
public class RobotContainer {

  private final TurretSubsystem turretSubsystem = new TurretSubsystem();
  private final ShooterSubsystem shooterSubsystem = new ShooterSubsystem();
  private final ClimberSubsystem climberSubsystem = new ClimberSubsystem(); 
  private final IntakeSubsystem intakeSubsystem = new IntakeSubsystem();


  private final CommandXboxController controller = new CommandXboxController(0);

  // CONSTRUCTOR yah
  public RobotContainer() {


    NamedCommands.registerCommand("TurretAim", Commands.run(() -> {
                        turretSubsystem.aimAtTag();
                }, turretSubsystem));
    NamedCommands.registerCommand("Intake", Commands.run(() -> {
                        intakeSubsystem.setIntakeDown();
                        intakeSubsystem.runIntake(0.35);
                }, intakeSubsystem));    
    NamedCommands.registerCommand("StopIntake", Commands.run(() -> {
                        intakeSubsystem.stopIntake();
                        intakeSubsystem.setIntakeUp();
                }, intakeSubsystem));
    NamedCommands.registerCommand("Shoot", Commands.run(() -> {
                        shooterSubsystem.runFullShooter(0.45);
                }, shooterSubsystem));
    NamedCommands.registerCommand("StopShoot", Commands.run(() -> {
                        shooterSubsystem.stopAll();
                }, shooterSubsystem));
    // ========== SINGLE CONTROLLER - ALL ROBOT CONTROLS ==========
    // NOTE: All speeds set to LOW values for safe testing

    // TRIGGERS
    // Left Trigger - Turret auto-aim at AprilTag
    controller.leftTrigger()
     .whileTrue(
        new StartEndCommand(
          () -> turretSubsystem.aimAtTag(),
          () -> turretSubsystem.stop(),
          turretSubsystem));

  // Left trigger - Full shooter (flywheels + feeder + indexer)
    controller.leftTrigger()
    .whileTrue(
        new StartEndCommand(
            () -> shooterSubsystem.runFullShooter(0.45),  // Reduced from 0.7
            () -> shooterSubsystem.stopAll(),
            shooterSubsystem));

    // FACE BUTTONS
    // Y - Run shooter flywheels only (spin up)
    controller.y()
    .whileTrue(
        new StartEndCommand(
            () -> shooterSubsystem.runFlywheels(0.3),  // Reduced from 0.7
            () -> shooterSubsystem.stopFlywheels(),
            shooterSubsystem));

    // X - Run intake rollers
    controller.x()
    .whileTrue(
        new StartEndCommand(
            () -> intakeSubsystem.runIntake(0.35),  // Reduced from 0.5
            () -> intakeSubsystem.stopIntake(),
            intakeSubsystem));

    // B - Intake deploy up
    controller.b()
    .whileTrue(
        new StartEndCommand(
            () -> intakeSubsystem.setIntakeUp(),
            () -> {},
            intakeSubsystem));
            
    // A - Intake deploy down
    controller.a()
    .whileTrue(
        new StartEndCommand(
            () -> intakeSubsystem.setIntakeDown(),
            () -> {},
            intakeSubsystem));

    // BUMPERS
    // Left Bumper - Run feeder only
    controller.leftBumper()
    .whileTrue(
        new StartEndCommand(
            () -> shooterSubsystem.runFeeder(0.25),  // Reduced from 0.5
            () -> shooterSubsystem.stopFeeder(),
            shooterSubsystem));

    // Right Bumper - Run indexer only
    controller.rightBumper()
    .whileTrue(
        new StartEndCommand(
            () -> shooterSubsystem.runIndexer(0.25),  // Reduced from 0.4
            () -> shooterSubsystem.stopIndexer(),
            shooterSubsystem));

    // D-PAD (POV) - CLIMBER CONTROLS
    // POV Up (0°) - Elevator UP
    controller.povUp()
      .whileTrue(
          new StartEndCommand(
              () -> climberSubsystem.elevatorUp(0.3),  // Reduced from 0.6
              () -> climberSubsystem.stopElevator(),
              climberSubsystem
          )
      );

    // POV Down (180°) - Elevator DOWN
    controller.povDown()
      .whileTrue(
          new StartEndCommand(
              () -> climberSubsystem.elevatorDown(0.3),  // Reduced from 0.6
              () -> climberSubsystem.stopElevator(),
              climberSubsystem
          )
      );

    // POV Right (90°) - Climb motors forward
    controller.povRight()
      .whileTrue(
          new StartEndCommand(
              () -> climberSubsystem.runClimb(0.25),  // Reduced from 0.5
              () -> climberSubsystem.stopClimb(),
              climberSubsystem
          )
      );

    // POV Left (270°) - Climb motors reverse
    controller.povLeft()
      .whileTrue(
          new StartEndCommand(
              () -> climberSubsystem.runClimb(-0.25),  // Reduced from -0.5
              () -> climberSubsystem.stopClimb(),
              climberSubsystem
          )
      );

    // BACK/START BUTTONS - SERVO CONTROLS
    // Back button - Servos retracted
    controller.back()
      .onTrue(new InstantCommand(() -> climberSubsystem.setServoRetracted(), climberSubsystem));

    // Start button - Servos extended
    controller.start()
      .onTrue(new InstantCommand(() -> climberSubsystem.setServoExtended(), climberSubsystem));


    // ========== DEFAULT COMMANDS ==========

    // Turret default: Manual control with right stick, auto-aim when centered
    turretSubsystem.setDefaultCommand(new RunCommand(
        () -> {
          double input = controller.getRightX();
          if (Math.abs(input) > 0.1) {
            turretSubsystem.rotate(input * 0.15); // Reduced from 0.2 for testing
          } else {
            turretSubsystem.aimAtTag(); // Auto-aim when stick centered
          }
        },
        turretSubsystem));

  }

  private static RobotContainer m_robotContainer = new RobotContainer();

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  // The robot's subsystems

  // Joysticks

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
   * The container for the robot. Contains subsystems, OI devices, and commands.
   */

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
  // Configure the button bindings

  // Configure default commands
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

  // Configure autonomous sendable chooser
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

  // m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

  // SmartDashboard.putData("Auto Mode", m_chooser);

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be
   * created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing
   * it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {

    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
    // Create some buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
   */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }

}
