// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
import java.io.File;

import com.pathplanner.lib.auto.AutoBuilder;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.RobotBase;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.Constants.DrivebaseConstants;
import frc.robot.Constants.OperatorConstants;
import frc.robot.subsystems.SwerveSubsystem;
import swervelib.SwerveInputStream;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import edu.wpi.first.wpilibj2.command.StartEndCommand;
import com.revrobotics.RelativeEncoder;
import com.revrobotics.spark.SparkLowLevel.MotorType;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.RunCommand;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * This class is where the bulk of the robot should be declared. Since
 * Command-based is a "declarative" paradigm, very
 * little robot logic should actually be handled in the {@link Robot} periodic
 * methods (other than the scheduler calls).
 * Instead, the structure of the robot (including subsystems, commands, and
 * trigger mappings) should be declared here.
 * This class is where the bulk of the robot should be declared. Since
 * Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in
 * the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of
 * the robot
 * (including subsystems, commands, and button mappings) should be declared
 * here.
 */
public class RobotContainer {
        private final SendableChooser<Command> autoChooser;

        // Controllers
        final CommandXboxController driverXbox = new CommandXboxController(0);
        final CommandXboxController testerXbox = new CommandXboxController(5);

        // Swerve subsystem
        private final SwerveSubsystem drivebase = new SwerveSubsystem(new File(Filesystem.getDeployDirectory(),
                        "swerve/Robot2025"));

        /**
         * Converts driver input into a field-relative ChassisSpeeds input stream that
         * is
         * controlled by angular velocity.
         */
        SwerveInputStream driveAngularVelocity = SwerveInputStream.of(drivebase.getSwerveDrive(),
                        () -> driverXbox.getLeftY() * -1,
                        () -> driverXbox.getLeftX() * -1)
                        .withControllerRotationAxis(() -> driverXbox.getRightX() * -1)
                        .deadband(OperatorConstants.DEADBAND)
                        .scaleTranslation(1.0)
                        .scaleRotation(0.5)
                        .allianceRelativeControl(true)
                        .robotRelative(false);

        /**
         * Clone's the angular velocity input stream and converts it to a robotRelative
         * input stream.
         */
        SwerveInputStream driveRobotOriented = driveAngularVelocity.copy().robotRelative(true)
                        .allianceRelativeControl(false);

        // Simulation input streams
        SwerveInputStream driveAngularVelocitySim = SwerveInputStream.of(drivebase.getSwerveDrive(),
                        () -> -driverXbox.getLeftY(),
                        () -> -driverXbox.getLeftX())
                        .robotRelative(false)
                        .withControllerRotationAxis(() -> driverXbox.getRightX() * -1)
                        .deadband(OperatorConstants.DEADBAND)
                        .scaleTranslation(DrivebaseConstants.DriveFastScale)
                        .allianceRelativeControl(true);

        SwerveInputStream driveRobotAngularVelocitySim = driveAngularVelocitySim.copy().robotRelative(true)
                        .allianceRelativeControl(false);

        // Robot oriented drive commands for TEST mode
        Command driveRobotOrientAngularVelocity = drivebase.driveRobotOriented(driveRobotOriented);
        Command driveRobotOrientAngularVelocitySim = drivebase.driveRobotOriented(driveRobotAngularVelocitySim);

        /**
         * The container for the robot. Contains subsystems, OI devices, and commands.
         */
        public RobotContainer() {
                // Register dummy commands for PathPlanner (can be replaced with real commands
                // later)
                // Example: NamedCommands.registerCommand("ExampleCommand",
                // Commands.print("Example"));

                // Build auto chooser (will be empty until you create PathPlanner autos)
                autoChooser = AutoBuilder.buildAutoChooser();
                SmartDashboard.putData("Auto Chooser", autoChooser);

                configureBindings();
                DriverStation.silenceJoystickConnectionWarning(true);
        }

        /**
         * Use this method to define your trigger->command mappings.
         */
        private void configureBindings() {
                // Default drive mode is field oriented
                drivebase.setDefaultCommand(
                                RobotBase.isSimulation() ? drivebase.driveFieldOriented(driveAngularVelocitySim)
                                                : drivebase.driveFieldOriented(driveAngularVelocity));

                // Driver controls
                driverXbox.start().onTrue((Commands.runOnce(drivebase::zeroGyro)));
                driverXbox.back().whileTrue(drivebase.centerModulesCommand());

                // Precision mode when left trigger is pressed
                driverXbox.leftTrigger().onTrue(Commands.runOnce(
                                () -> driveAngularVelocity
                                                .scaleTranslation(Constants.DrivebaseConstants.DrivePrecisionScale)
                                                .scaleRotation(0.3)))
                                .onFalse(Commands.runOnce(
                                                () -> driveAngularVelocity.scaleTranslation(
                                                                Constants.DrivebaseConstants.DriveFastScale)
                                                                .scaleRotation(0.5)));

                // Robot-relative driving when right trigger is pressed
                driverXbox.rightTrigger().onTrue(Commands.runOnce(
                                () -> driveAngularVelocity.robotRelative(true)
                                                .allianceRelativeControl(false)))
                                .onFalse(Commands.runOnce(
                                                () -> driveAngularVelocity.robotRelative(false)
                                                                .allianceRelativeControl(true)));
        }

        public void ZeroGyro() {
                drivebase.zeroGyroWithAlliance();
        }

        public Command getAutonomousCommand() {
                return autoChooser.getSelected();
        }

        public void setDriveMode() {
                configureBindings();
        }

        public void setMotorBrake(boolean brake) {
                drivebase.setMotorBrake(brake);
        }
}

  private final TurretSubsystem turretSubsystem = new TurretSubsystem();
  private final ShooterSubsystem shooterSubsystem = new ShooterSubsystem();
  private final ServoSubsystem servoSubsystem = new ServoSubsystem();


  private final CommandXboxController driverController = new CommandXboxController(0);
  // private final CommandXboxController operatorController = new
  // CommandXboxController(1);

  // CONSTRUCTOR yah
  public RobotContainer() {

    // turretSubsystem.setDefaultCommand(
    // new AimTurretCommand(turretSubsystem)
    // );

    driverController.a()
      .whileTrue(
          new StartEndCommand(
             () -> shooterSubsystem.runShooter(0.4),
             () -> shooterSubsystem.stopShooter(),
              shooterSubsystem));
    
    // driverController.b()
    // .whileTrue(
    // new StartEndCommand(
    // () -> turretSubsystem.aimAtTag(),
    // () -> turretSubsystem.stop(),
    // shooterSubsystem));

    driverController.x()
    .whileTrue(
        new StartEndCommand(
            () -> servoSubsystem.levelOne(),   // on start
            () -> servoSubsystem.levelOne(),   // on end
            servoSubsystem              // requirement
        )
    );

  driverController.y()
    .whileTrue(
        new StartEndCommand(
            () -> servoSubsystem.LevelTwo(),   // on start
            () -> servoSubsystem.LevelTwo(),   // on end
            servoSubsystem              // requirement
        )
    );

    driverController.b()
    .whileTrue(
        new StartEndCommand(
            () -> servoSubsystem.LevelThree(),   // on start
            () -> servoSubsystem.LevelThree(),   // on end
            servoSubsystem              // requirement
        )
    );

LinearServoTest actuator =
    new LinearServoTest(0, 0); // PWM 0, Analog 0

actuator.setDefaultCommand(
    new RunCommand(
        () -> {
            double joystick = -driverController.getLeftY();

            // DEAD BAND
            if (Math.abs(joystick) < 0.1) {
                actuator.holdCurrentPosition();
            } else {
                // CLAMP happens inside subsystem
                actuator.manualSpeed(joystick);
            }
        },
        actuator
    )
);



    turretSubsystem.setDefaultCommand(new RunCommand(
        () -> {
          double input = driverController.getRightX();
          // System.out.println(input);
          // deadband
          if (Math.abs(input) > 0.1) {
            turretSubsystem.rotate(input * 0.2); // limit speed
          } else {
            System.out.println("AIMING");
            turretSubsystem.aimAtTag();
          }

        },
        turretSubsystem));

  }

  private static RobotContainer m_robotContainer = new RobotContainer();

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  // The robot's subsystems

  // Joysticks

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
   * The container for the robot. Contains subsystems, OI devices, and commands.
   */

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
  // Configure the button bindings

  // Configure default commands
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

  // Configure autonomous sendable chooser
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

  // m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

  // SmartDashboard.putData("Auto Mode", m_chooser);

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be
   * created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing
   * it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {

    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
    // Create some buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
   */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }

}
